### ISSUE TITLE
Missing training files

### ISSUE THREAD

**Issue by TommasoBorghesi612** [billyblu2000/Chorderator#7]
Hi, first of all amazing work, i really love this repo and i had a lot of fun creating accompaniment with your model.

I was hoping i could retrain the model on some chord progressions i have but i could not find any script for training.
I saw that there is a TrainingInterface class inside /amc_dl/torch_plus/module.py that seems to be made for it but i could not find anywhere a point at wich was called.

Of course i can understand if it was your choice not to publicly publish the trainig pipeline, i just would like to know if it is the case or if i am missing something.

In any case, good job again and have a nice day.

**Comment by billyblu2000** [comment]
AccoMontage2 uses a **rule-based** algorithm to harmonize the melody, then uses [AccoMontage](https://github.com/zhaojw1998/accomontage) / [Polyphonic chord-texture disentanglement](https://github.com/ZZWaang/polyphonic-chord-texture-disentanglement) to apply texture to the selected chord progression and achieve piano accompaniment. That is to say, you cannot 'train' the model on some new chord progression, unfortunately. It is tough to test the AccoMontage2 model on a new dataset because the data preprocessing pipeline is very tedious, and we don't have a function to control this pipeline. But if you are really interested in adding new progressions, you are still welcome to study the code and modify it freely. We have already pushed all the related code to the repo.

The training interface you saw actually belongs to [AccoMontage ](https://github.com/zhaojw1998/accomontage)/ [Polyphonic chord-texture disentanglement](https://github.com/ZZWaang/polyphonic-chord-texture-disentanglement). You can also visit their repo if you are interested in their project.

**Comment by TommasoBorghesi612** [comment]
Ok, thank you for your explanation so, i knew the original Accomontage repo but i was missing Polyphonic chord-texture disentanglement, i am for sure going to check that.

Thank you again for your work, i am closing this issue, have a nice day.
